[env]
term = "xterm-256color"

[general]
import = [
"~/.config/alacritty/themes/github_light_high_contrast.toml",
]
live_config_reload = true

[window]
decorations = "None"
decorations_theme_variant = "Dark"

[font]
normal.family = "Mononoki Nerd Font"
bold.family = "Mononoki Nerd Font"
italic.family = "Mononoki Nerd Font"
bold_italic.family = "Mononoki Nerd Font"

size = 11
