# /home/niklasv/.config/tmuxinator/settingsUi.yml

name: settings-ui
root: ~/Programming/snapaddy-settings-ui/

startup_window: Editor
on_project_first_start: lazygit

windows:
  - Editor: nvim
  - Terminal:
  - Server: npm ci && npm run start
