# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-2e3b5a60-7251-4b30-87f1-aa7b07118473";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-2e3b5a60-7251-4b30-87f1-aa7b07118473".device = "/dev/disk/by-uuid/2e3b5a60-7251-4b30-87f1-aa7b07118473";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2497-47B7";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-80113675-6c6b-4a0a-8a6f-ed0186ec98ba"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
