# Set prefix to Alt+A
unbind C-b
set -g prefix M-a

# True term colors
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Faster key repetition (instant <Esc>)
set -s escape-time 0

# Theme
set -g status-left-length 40
set -g status-justify centre
set -g status-bg "#e0e0e0"
set -g status-fg "#000000"
setw -g window-status-current-style "fg=#ffffff,bg=#1f2328"

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Scroll history
setw -g mouse on

# Window switching
bind-key -n M-1 selectw -t 1
bind-key -n M-2 selectw -t 2
bind-key -n M-3 selectw -t 3
bind-key -n M-4 selectw -t 4
bind-key -n M-5 selectw -t 5
bind-key -n M-6 selectw -t 6
bind-key -n M-7 selectw -t 7
bind-key -n M-8 selectw -t 8
bind-key -n M-9 selectw -t 9

# Pane switching
